# *Simplex Method*

In [ ]:
c = [.1375,141.1153,.0281,1.0576,.3307, .5057, .0169, .00807,5.9038, .00288,0.0,0.0,0.0, 0.0,0.0,0.0, 0.0,0.0,0.0,0.0] #equation
A = [[0.0,0.0,0.0,55.0,17.2,26.3,0.88,0.42,0.0,0.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
     [1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
     [0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
     [0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
     [1.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],
     [1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0],
     [1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0],
     [1.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],
     [1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0],
     [1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0, 0.0,0.0,1.0,0.0],
     [1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0]]#restrictions
b = [100.0,1.0,0.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0] 

In [ ]:
print(len(b))

10


In [ ]:
import numpy as np
c = np.array(c, dtype = 'float32') #ecuación, nota: incluir variables apoyo
A = np.array(A, dtype = 'float32') #restricciones
b = np.array(b, dtype = 'float32') #valores de igualación de restricciones

In [ ]:
def Simplex(A, b, c):
    '''Takes input vars, computs corresponding values,
    then uses while loop to iterate until a basic optimal solution is reached.
    RETURNS: cbT, cbIndx, cnT, cnIndx, bHat, cnHat.
    cbT, cbIndex is final basic variable values, and indices
    cnT, cnIndex is final nonbasic variable values and indices
    bHat is final solution values, 
    cnHat is optimality condition'''
    
    #sizes of basic and nonbasic vectors
    basicSize = A.shape[0] # restricciones
    nonbasicSize = A.shape[1] - basicSize #n-m, number of variables
        
   #para recuperar indices
    cindx = [i for i in range(0, len(c))]
    
    #matrices apoyo
    cbT = np.array(c[nonbasicSize:])

    cnT = np.array(c[:nonbasicSize])
    
    # run core simplex method until reach the optimal solution
    while True:
        
        
        cbIndx = cindx[nonbasicSize:]
        cnIndx = cindx[:nonbasicSize]
        
        B = A[:, cbIndx]
        Binv = np.linalg.pinv(B)

        
        N = A[:, cnIndx]
        
        bHat = np.matmul(Binv,b)
        yT = cbT @ Binv
        
        # se utiliza una matriz identidad como apoyo para la busqueda del mínimo
        cnHat = cnT - (yT @ N)
        
        # indice del mínimo
        cnMinIndx = np.argmin(cnHat)

        if(all(i>=0 for i in cnHat)):
            # use cbIndx to get index values of variables in bHat, and the corresponding index
            # values in bHat are the final solution values for each of the corresponding variables
            # ie value 0 in dbIndx corresponds with first variable, so whatever the index for the 0 is
            # is the index in bHat that has the solution value for that variable.
            return cbT, cbIndx, cnT, cnIndx, bHat, cnHat
        
        # this is the index for the column of coeffs in a for the given variable
        indx = cindx[cnMinIndx]

        Ahat = Binv @ A[:, indx]
        

        ratios = []
        for i in range(0, len(bHat)):
            Aval = Ahat[i]
            Bval = bHat[i]

            # don't look at ratios with val less then or eqaul to 0, append to keep index
            if(Aval <= 0):
                ratios.append(10000000)
                continue
            ratios.append(Bval / Aval)

        ratioMinIndx = np.argmin(ratios)

        #switch basic and nonbasic variables using the indices.
        cnT[cnMinIndx], cbT[ratioMinIndx] = cbT[ratioMinIndx], cnT[cnMinIndx]
        # switch global index tracker indices
        cindx[cnMinIndx], cindx[ratioMinIndx + nonbasicSize] = cindx[ratioMinIndx + nonbasicSize], cindx[cnMinIndx]
        

Simplex(A, b, c)

(array([0.00288, 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
        0.     , 0.     , 0.     , 0.     ], dtype=float32),
 [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 array([1.375000e-01, 1.411153e+02, 2.810000e-02, 1.057600e+00,
        3.307000e-01, 5.057000e-01, 1.690000e-02, 8.070000e-03,
        5.903800e+00], dtype=float32),
 [0, 1, 2, 3, 4, 5, 6, 7, 8],
 array([666.6666,   1.    ,   0.7   ,   1.    ,   1.    ,   1.    ,
          1.    ,   1.    ,   1.    ,   1.    ,   1.    ], dtype=float32),
 array([1.3750000e-01, 1.4111530e+02, 2.8100001e-02, 1.6000271e-03,
        4.5999885e-04, 7.4005127e-04, 4.0009618e-06, 6.0014427e-06,
        5.9038000e+00], dtype=float32))

In [ ]:
val = 0
a_1 = [.1375,141.1153,.0281,1.0576,.3307,.5057, .0169, .00807,5.9038, .00288]
val_1 = [666.6666,   1.    ,   0.7   ,   1.    ,   1.    ,   1.    ,
          1.    ,   1.    ,   1.    ,   1.    ,   1.    ]
for i in range(len(a_1)): 
  val += a_1[i]*val_1[i]
print(val)

240.6272775


# *Gradient descent*

In [ ]:
from sympy.strategies.rl import new
from traitlets.config.application import deepcopy
from sympy.matrices import determinant
from types import new_class
from sympy import *
from sympy.abc import h, c, g, u, p, f, a, r, k, i, b,c,d,e,f,g,h,m,n,o,q
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import math
import time
%matplotlib inline
init_printing(use_latex ='mathjax')

class Graph:
    def __init__(self):
        self.fig = plt.figure()
        self.ax = plt.axes(projection='3d')

    def evalFunction(self, X, Y):
        return X**2 + 2*Y

    def point3D(self, X, Y):
        Z = self.evalFunction(X, Y)
        #ax = plt.axes(projection='3d')
        self.ax.scatter(X, Y, Z, c='blue', cmap='viridis', linewidth=0.7)

    def displayPlot(self):
        plt.show()


    #
    def surfacePlot3D(self, f):
        x = np.linspace(-10, 10, 300)
        y = np.linspace(-10, 10, 300)

        # Grid de los ejes X y Y
        X, Y = np.meshgrid(x, y)

        # Evaluar función original
        Z = self.evalFunction(X, Y)

        #ax = plt.axes(projection='3d')
        self.ax.plot_surface(X, Y, Z, rstride=1, cstride=1,
                cmap='viridis', edgecolor='none')
        self.ax.set_title('Función original');
    
    def plot2D(self, f, start, end):
        X = np.linspace(start,end, 300)
        Y = np.zeros_like(X)
        for i in range(len(X)):
            Y[i] = f.subs(x, X[i])
        plt.plot(X, Y)

            

class Gradiente():
    def __init__(self):
        """self.x0 = x0
        self.y0 = y0"""

    #Paso 1. Calcular una derivada parcial
    def calcDer(self, f, var):
      return f.diff(var)
    #Paso 2. Calcular múltiples derivadas parciales 
    def calcularDers(self, f, vars):
        ders1 = []
        ders2 = []
        for var in vars:
            i = 0
            ders1.append(f.diff(var))
            ders2.append(ders1[i].diff(var))
            i+=1
        return ders1, ders2  
    #Función utilidad para el paso 3
    def generarMatrizNxN(self, n): 
      mat = [[0 for i in range(n)] for i in range(n)]
      return mat 
    def smaller_matrix(self, H, row, column): 
      new_matrix = deepcopy(H)
      new_matrix.remove(H[row])
      for i in range(len(new_matrix)): 
        new_matrix[i].remove(new_matrix[i][column])
      return new_matrix
    #Paso 3. Calcular el determinante de la matriz Hessiana  
    def generarHessiana(self,f, vars):
        n = len(vars)
        H = self.generarMatrizNxN(n)
        for i in range(len(vars)):
            for j in range(len(vars)):
                d1 = f.diff(vars[i])
                H[i][j] = d1.diff(vars[j])
        return H #Función para generar la matriz Hessiana sobre la que se calculará el determinante
    #Calcular el determinante de la Hessiana
    def determinanteNxN(self,H):
      rows_size = len(H)
      for row in H: 
        if len(row) != rows_size: 
          return None
      if rows_size == 2: 
        simple_determinant = H[0][0] * H[1][1] - H[1][0] * H[0][1]
        return simple_determinant
      else: 
        answer = 0 
        num_columns = rows_size
        for j in range(num_columns): 
          cofactor = (-1) **j * H[0][j] * determinant(self.smaller_matrix(H, 0, j))
          answer += cofactor 
        return answer
    #Paso 4. Ascenso pronunciado más optimo 
    #Función de cambio de variables 
    def calculoValorGradiente(self, punto,vars, ders1, helpvars): 
        grad = []
        temp = []
        module = 0
        for i in range(len(punto)): 
          temp.append((vars[i], punto[i]))
        for j in range(len(ders1)):
          grad.append(-ders1[j].subs(temp)* helpvars[j])
          module += (-ders1[j].subs(temp))**2
        module = math.sqrt(module)            
        return grad, module 
    def calculoEcuacionGradiente(self,punto,vars,ders1, helpvars, f): 
      temp = []
      hPos = []
      grad, module = self.calculoValorGradiente(punto,vars, ders1,helpvars)
      for i in range(len(grad)):
        temp.append(punto[i] + grad[i].subs(helpvars[i], h))
      for j in range(len(vars)):
        hPos.append((vars[j],temp[j]))
      function = simplify(f.subs(hPos))        
      return function
    def golden_search(self, f, a, b, tol, max):
        # Initialize counter
        cont = 0
        d = ((np.sqrt(5) - 1) / 2) * (b - a)
        x1 = a + d
        x2 = b - d
        # Calculate point
        if max == False:
            while (b - a) > tol:
                cont = cont + 1
                if f.subs(h, x1) < f.subs(h, x2):
                    a = x2
                    x2 = x1
                if f.subs(h, x1) > f.subs(h, x2):
                    b = x1
                    x1 = x2
        else:
            while (b - a) > tol:
                d = ((np.sqrt(5) - 1) / 2) * (b - a)
                x1 = a + d
                x2 = b - d
                cont = cont + 1
                if f.subs(h, x1) > f.subs(h, x2):
                    a = x2
                    x2 = x1
                if f.subs(h, x1) < f.subs(h, x2):
                    b = x1
                    x1 = x2

        return x2
    def evaluateDerivate(self, vars, punto, ders1):
        der_1_eval = []
        temp = []
        for n in range(len(punto)):
          temp.append((vars[n], punto[n]))
        for m in range(len(temp)):
          der_1_eval.append(ders1[m].subs(temp))
        return der_1_eval
    def euclideanDistance(self, ders1, punto, vars): 
          temp = []
          dist = []
          val = 0
          for i in range(len(punto)):
            temp.append((vars[i],punto[i]))
          for j in range(len(temp)): 
            dist.append(ders1[j].subs(temp) * ders1[j].subs(temp))
            val += ders1[j].subs(temp) * ders1[j].subs(temp)
          return -sqrt(val)
    def ascensoOptimo(self, HessMat, ders2, tol, maxIter, punto, ders1, vars, help_vars, f, x0, y0):
      error = float('inf')
      iter = 0 
      #if self.determinanteNxN(HessMat) > 0 and ders2[0] < 0: 
        #max = True
      #else: 
        #max = False
      while error > tol and iter < maxIter:
          error = self.euclideanDistance(ders1, punto, vars)
          der_1_eval = self.evaluateDerivate(vars, punto, ders1)
          fh = self.calculoEcuacionGradiente(punto,vars,ders1,help_vars,f)
          h = self.golden_search(fh, x0, y0, tol, True)
          for g in range(len(vars)): 
            punto[g] = punto[g] + h*der_1_eval[g]
          iter += 1
      return punto, error


def main():

    # Definición de objetos
    objGrad = Gradiente()
    
    # function
    func = (7.15*h + 7338*c + 1.5*g + 17.2*p + 26.3*f + 0.88*a + 0.42*r + 307*k + 0.15*i)/52
    tol = 0.001
    maxIter = 1000
    # Define a list of variables
    vars = [h, c, g, u, p, f, a, r, k, i]
    help_vars = [b,c,d,e,f,g,h,m,n,o]
    print('Vars', len(vars), 'Help', len(help_vars))
  

    #puntos iniciales
    punto = [1, 1, 1,1,1,1,1,1,1,1]
    x0 = -1
    y0 = 1
    
    start_time_2 = time.time()

    # Calcular primeras y segundas derivadas
    ders1, ders2 = objGrad.calcularDers(func, vars)
    # Calculamos la matriz Hessiana
    HessMat = objGrad.generarHessiana(func, vars)

    fh = objGrad.calculoEcuacionGradiente(punto,vars,ders1,help_vars,func)

    puntoOptimo, error = objGrad.ascensoOptimo(HessMat, ders2,tol, maxIter, punto, ders1, vars, help_vars, func, x0, y0)

    end_time_2 = time.time()
    time_taken_2 = end_time_2 - start_time_2


    print('El punto óptimo está en: ', puntoOptimo)
    print('Con tiempo de solución de: ', time_taken_2, 's')


    temp = []
    val = 0
    for j in range(len(puntoOptimo)):
      temp.append((vars[j],puntoOptimo[j]))
    val = func.subs(temp)
    print('Valor de métano en el punto óptimo', val)

    

if __name__ == "__main__":
  main()

Vars 10 Help 10
El punto óptimo está en:  [0.862577009235070, -140.036350522106, 0.971170001937427, 1, 0.669416022215833, 0.494514033969558, 0.983086401136624, 0.991927600542480, -4.90053960347322, 0.997117000193743]
Con tiempo de solución de:  0.4243471622467041 s
Valor de métano en el punto óptimo -19789.5698200194
